### ISSUE TITLE
Using Particle.js

### ISSUE THREAD

**Issue by Nikronic** [Nikronic/nikronic.github.io#11]
https://vincentgarreau.com/particles.js/

**Comment by matteobruni** [comment]
Lighter alternative: https://github.com/matteobruni/tsparticles

**Comment by Nikronic** [comment]
@matteobruni Thank you, great job!

**Comment by lindelof** [comment]
> Lighter alternative: https://github.com/matteobruni/tsparticles

Not too sincere author

**Comment by Nikronic** [comment]
@lindelof it seems you have a lot of experience about particles too. Unfortunately, I know nothing about web!

**Comment by lindelof** [comment]
Thank you very much for your reply, your project is great. tsparticles borrows other people’s projects, the author doesn’t seem to thank the author
