### ISSUE TITLE
Grammar Fix/Improvement

### ISSUE THREAD

**Issue by Nikronic** [Nikronic/nikronic.github.io#3]
Hi, actually I am not a native English speaker, so I would be appreciated for any help even a typo.
Thank you.

**Comment by pablostellet** [comment]
Hi, I think I can help you in it.

It's just for documentation or do you also need on html and js files?

**Comment by Nikronic** [comment]
@pablostellet Thank you so much.
We can focus on index.html file as it contains all information.

**Comment by pablostellet** [comment]
All right, deleted my comment by mistake.
Gonna fork it :)
