### ISSUE TITLE
Design/Grammar/Word Fix/Improvement

### ISSUE THREAD

**Issue by Nikronic** [Nikronic/nikronic.github.io#4]
I have hard-coded many parts as I am not a web developer and the code may seem ridiculous even I have used a template and googled a lot!
I would be grateful for any help about fixing issues related to design or any improvement or suggestion.  :-)

**Comment by mgeorgiou** [comment]
I can take a look

**Comment by Nikronic** [comment]
@mgeorgiou It would be great, thank you so much for your help.

**Comment by mgeorgiou** [comment]
No problem @Nikronic. PR ready for review https://github.com/Nikronic/nikronic.github.io/pull/9
