### ISSUE TITLE
make tile wider in mobile view

### ISSUE THREAD

**Issue by Nikronic** [Nikronic/nikronic.github.io#5]
I think if the panel be a little wider;It is more readable. 
It is in the `project experience` section and for mobile view. I tried but I could not realize responsive stuff!
Thank you
![image](https://user-images.githubusercontent.com/32401852/67529415-f4a72e80-f6c8-11e9-9920-e56831175c30.png)

**Comment by jitusd9** [comment]
I am doing this

**Comment by Nikronic** [comment]
@jitusd9 Thank you so much for your time. Good luck!
