### ISSUE TITLE
Align 'stars' to the right of its container

### ISSUE THREAD

**Issue by Nikronic** [Nikronic/nikronic.github.io#6]
Aligning 'star' icons so the size of text does not make them stay in different places.
![image](https://user-images.githubusercontent.com/32401852/67529754-f0c7dc00-f6c9-11e9-95f7-78ddcdcb65b7.png)
As you can see, because of texts' different sizes, starts are not aligned.
Thank you for your help.

**Comment by sercopi** [comment]
Hi, could I work on this as my first contribution to Hacktobesfest? :)

**Comment by Nikronic** [comment]
@sercopi Yes sure, I am so grateful for your help.

**Comment by gmhabchi** [comment]
Oops, I've already done it

**Comment by sercopi** [comment]
> 
> 
> Oops, I've already done it

It´s ok, don´t worry :D

**Comment by Nikronic** [comment]
@gmhabchi @sercopi Sorry guys I did not know!
@sercopi may be you can work on #5 ? I do know it is hard or easy as I could not really fix it.

**Comment by Nikronic** [comment]
PR #7
